### PR TITLE
fix: fix mistake in vkcs_kubernetes_node_group docs

### PR DESCRIPTION
**Pull request by kvendingoldo**

### CODE REVIEW

**Review by ftersin — CHANGES_REQUESTED** [review]
rebase on master, pls

**Comment by paaanic** [comment]
Close due to inactivity.

**Comment by kvendingoldo** [comment]
Let me reopen it, I will rebase change

**Comment by paaanic** [comment]
It seems that these changes are completely out of date, and, by the way, docs are auto-generated, thus, for the future, fixes like these should be done in the schema definition of resource/data source directly in the source code. Thank you for participating in improving our project and I look forward to your future contributions!

**Pull request closed without merging**
